#!/bin/ash
#
# entrypoint: Located at `/etc/container/entrypoint` this script is the custom
#             entry for a container as called by `/usr/bin/container-entrypoint` set
#             in the upstream [alpine-container](https://github.com/gautada/alpine-container).
#             The default template is kept in
#             [gist](https://gist.github.com/gautada/f185700af585a50b3884ad10c2b02f98)

ENTRYPOINT_PARAMS="$@"
. /etc/profile

app_version() {
 echo "1.0.0"
}

if [ -z "$@" ] ; then
  log "-i" "entrypoint" "default"
  /usr/bin/pgrep python3 > /dev/null
  TEST=$?
  if [ $TEST -eq 1 ] ; then
   log "-i" "entrypoint" "Blocking application - blackhole($(app_version))"
   # /usr/bin/uvicorn blackhole:app  --host 0.0.0.0  --port 8080 --reload
   cd /home/blackhole
   /usr/bin/python3 blackhole.py
  fi
  return 1
else
 log "-i" "entrypoint" "Override default($ENTRYPOINT_PARAMS)"
 log "-i" "entrypoint" "Detatched application - blackhole($(app_version))"
 # /usr/bin/uvicorn blackhole:app --host 0.0.0.0 --port 8080 --reload >> /mnt/volumes/container/_log 2>&1 &
  cd /home/blackhole
 /usr/bin/python3 blackhole.py >> /mnt/volumes/container/_log 2>&1 &
 return 0
fi

